- name: Build APK and AAB
        env:
          SKYMETER_KEYSTORE: ${{ github.workspace }}/keystore/skymeter.jks
          SKYMETER_STORE_PASSWORD: ${{ steps.ks.outputs.pass }}
          SKYMETER_KEY_ALIAS: ${{ steps.ks.outputs.alias }}
          SKYMETER_KEY_PASSWORD: ${{ steps.ks.outputs.kpass }}
        run: ./gradlew assembleRelease bundleRelease --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: SkyMeter-release-apk
          path: app/build/outputs/apk/release/*.apk

      - uses: actions/upload-artifact@v4
        with:
          name: SkyMeter-release-aab
          path: app/build/outputs/bundle/release/*.aab
